routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes();

Route::get('/', function () { return view('home'); })->name('home');
Route::get('/login', function(){ return view('authentication/login'); })->name('login');
Route::get('/register', function(){ return view('authentication/register'); })->name('register');

Route::middleware(['auth'])->group(function () {
    Route::resource('users', 'UsersController');
    Route::resource('teams', 'TeamsController');
    Route::resource('tasks', 'TasksController');
    //checkTaskDeadline middleware is applied inside the TasksController

    Route::get('tasks/{task}/approve', 'TasksController@approve')->name('task.approve');
    Route::get('tasks/{task}/reassign', 'TasksController@reassign')->name('task.reassign');
    Route::get('tasks/{task}/resolve', 'TasksController@resolve')->name('task.resolve');
    Route::get('tasks/{task}/giveup', 'TasksController@giveup')->name('task.giveup');
    Route::get('tasks/{task}/assign', 'TasksController@assign')->name('task.assign');
});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use DateTime;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role','team_id', 'status', 'percentage'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * ACCESSORS
     */
    public function getAvatarAttribute()
    {
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }
    public function getCompletedTasksAttribute(){
        if($this->role == 'leader')
        {
            return $this->team->tasks()->where('status', 'RESOLVED')->get();
        }
        if($this->role == 'member')
        {
            return $this->tasks()->wherePivot('status', 'RESOLVED')->get();
        }
        return 'Role Mismatch';
    }
    public function getFailedTasksAttribute(){
        if($this->role == 'leader')
        {
            return $this->team->tasks()->where('status', 'UNRESOLVED')->get();
        }
        if($this->role == 'member')
        {
            return $this->tasks()->wherePivot('status', 'UNRESOLVED')->get();
        }
        return 'Role Mismatch';
    }

    /**
     * HELPER METHODS
     */

    /**
     * This function will calculate the percentage rate of the member as well as leader
     */
    public function updateUserStatus()
    {
        $getUserStatus = $this->status;
        if($this->tasks->count() > 0)
        {
            if($getUserStatus == 'VACANT')
            {
                $this->update(['status'=>'WORKING']);
            }
        }
        else
        {
            if($getUserStatus == 'WORKING')
            {
                $this->update(['status'=>'VACANT']);
            }
        }
    }
    public function calculatePercentage()
    {

        /**
         * PERCENTAGE VALUES FROM 100%
         * 1 : FOR MEMBER :
         *          successTasks = 50%;
         *          successTasksReport = 25%;
         *          reassign = 25%;
         * 2 : FOR LEADER :
         *          successTasks = 50%;
         *          successTasksReport = 20%;
         *          reassign = 20%;
         *          giveup = 10%;
         *
         * note : first i am calculating every condition in terms 100% then i am converting it to theri respected percentages mentioned above
         *
         * **************** REASSIGN CALCULATION ************
         * reassign rate some examples of calculation
         * formula : ($totalTasks->count() / ($reassignCount + $totalTasks->count()) ) * 100
         * 3 case :
         * 1 : 5tasks and 0 reassign and result we want is  100%
         *      sol : as per formula
         *              = ( 5 / (0+5) ) * 100
         *              = (5 / 5 ) * 100
         *              = 100%
         * 2 : 5tasks and 2 reassign and result we want is something and comparabel to above result
         *      sol : as per formula
         *              = ( 5 / (2+5) ) * 100
         *              = (5 / 7 ) * 100
         *              = 71.42%
         * 3 : 5tasks and 8 reassign and result we want is something and comparabel to above result
         *      sol : as per formula
         *              = ( 5 / (8+5) ) * 100
         *              = (5 / 13 ) * 100
         *              = 38.46%
         *
         * NOTE : these examples are based on the formula written at the star of this comment
         *
         * **************** SUCCESS TASKS REPORT CALCULATION ************
         * 1 : first iam calculating the time given
         * 2 : then iam calculating totalTimeTookToCompleteTask
         * 3 : then im dividing (2 by 1), and then multiply by 100 so that we get in terms of 100%
         * 4 : then if the successRate as given 20%
         *      so : (20 / totalTaskResolved)
         */

        //SOME CONSTANTS FOR CONDITION PERCENTAGE as mentioned in above comments
        /**
         * for leader : 50 + 20 + 20 + 10
         * for member : 50 + 25 + 25
         */
        //general percentages (i.e for members and employess are same)
        $RESOLVED_BY_ASSIGNED_PERCENTAGE = 50 / 100;
        //for leader
        $SUCCESS_TASKS_PERCENTAGE_FOR_LEADER = 20 / 100;
        $REASSIGN_TASKS_PERCENTAGE_FOR_LEADER = 20 / 100;
        $GIVEUP_TASKS_PERCENTAGE_FOR_LEADER = 10 / 100;
        //for member
        $SUCCESS_TASKS_PERCENTAGE_FOR_MEMBER = 25 / 100;
        $REASSIGN_TASKS_PERCENTAGE_FOR_MEMBER = 25 / 100;

        $totalTasks = null;
        $tasksCompleted = $this->completed_tasks;
        $tasksFailed = $this->failed_tasks;

        if($this->role == 'leader')
        {
            $totalTasks = $this->team->tasks_with_pivots;
            $reassignCount = 0;
            $giveupCount = 0;

            //calculating reassigncounts and giveupcounts
            foreach($this->team->tasks as $task)
            {
                foreach($task->record as $pivotRecord)
                {
                    $reassignCount += $pivotRecord->pivot->reassign_count;
                    if($pivotRecord->pivot->is_giveup)
                    {
                        $giveupCount ++;
                    }
                }
            }

            //calculating success percentage for each resolved task
            if($tasksCompleted->count() != 0)
            {
                $singleSuccessTaskPercentage = round( ($SUCCESS_TASKS_PERCENTAGE_FOR_LEADER / $tasksCompleted->count()), 3);
            }
        }
        elseif($this->role == 'member')
        {
            //here i will get the task with pivots
            $totalTasks = $this->tasks;
            $reassignCount = 0;

            //calculating reassigncounts
            foreach($totalTasks as $task)
            {
                $reassignCount += $task->pivot->reassign_count;
            }

            //calculating success percentage for each resolved task
            if($tasksCompleted->count() != 0)
            {
                $singleSuccessTaskPercentage = round( ($SUCCESS_TASKS_PERCENTAGE_FOR_MEMBER / $tasksCompleted->count()), 3);
            }
        }
        $totalTasksCount = $totalTasks->count();
        $totalPercentage = 0;

        //if there are tasks then only i will calculate otherwise i will not calculate
        if($totalTasksCount > 0)
        {

            // Calculating condition rates (without percentage conditions)
            $reassignRate = ($totalTasksCount / ($reassignCount + $totalTasksCount) ) * 100;
            $resolvedTasksByTotalTasksRate = ($tasksCompleted->count() / ($tasksCompleted->count() + $tasksFailed->count() )) * 100;

            //this for loopwill calculate all the resolved Tasks success percentage and will divide and add according to percentage for leader or person mentioned above
            $totalCompletedTasksSuccessInPercentage = 0;
            foreach($tasksCompleted as $task)
            {
                $totalTimeGiven = strtotime($task->deadline) - strtotime($task->created_at);
                $totalTimeTookToCompleteTask = strtotime($task->completed_at) - strtotime($task->created_at);
                $taskSuccessRate = ($totalTimeTookToCompleteTask / $totalTimeGiven) * 100;
                $totalCompletedTasksSuccessInPercentage += ($taskSuccessRate * $singleSuccessTaskPercentage);
            }

            //Percentage Calculation according to leader or member
            $resolvedTasksByTotalTasksPercentage = $resolvedTasksByTotalTasksRate * $RESOLVED_BY_ASSIGNED_PERCENTAGE;
            $totalPercentage = 0;
            if($this->role == 'leader')
            {
                $reassignTasksPercentage = $reassignRate * $REASSIGN_TASKS_PERCENTAGE_FOR_LEADER;

                $taskCountIntoTaskMemberCount = ($totalTasksCount * $this->team->members->count());
                $giveupTasksRate = ($taskCountIntoTaskMemberCount / ($taskCountIntoTaskMemberCount + $giveupCount) ) * 100;
                $giveupTasksPercentage = $giveupTasksRate * $GIVEUP_TASKS_PERCENTAGE_FOR_LEADER;

                $totalPercentageInFloat = $resolvedTasksByTotalTasksPercentage +
                                    $totalCompletedTasksSuccessInPercentage +
                                    $reassignTasksPercentage +
                                    $giveupTasksPercentage;
                $totalPercentage = round($totalPercentageInFloat, 3);
            }
            elseif($this->role == 'member')
            {
                $reassignTasksPercentage = $reassignRate * $REASSIGN_TASKS_PERCENTAGE_FOR_MEMBER;

                $totalPercentageInFloat = $resolvedTasksByTotalTasksPercentage +
                                    $totalCompletedTasksSuccessInPercentage +
                                    $reassignTasksPercentage;
                $totalPercentage = round($totalPercentageInFloat, 3);
            }
        }

        // dd(gettype($totalPercentage));

        /**
         * This method is called in :
         *      CheckAndUpdateTasksDeadline Middleware
         *      CheckTaskDeadline Middleware
         *      TaskController@approve
         *      TaskController@giveup
         */
        if($this->role == 'member')
        {
            $this->team->leader->calculatePercentage();
        }
        $this->update(['percentage' => $totalPercentage]);
    }
    public function bestEmployee()
    {

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function index()
    {
        if(auth()->user()->role == 'admin')
        {
            $users = User::paginate(10);
        }
        else
        {
            $users = auth()->user()->team->members()->paginate(10);
        }
        return view('users.index', compact(
            'users'
        ));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show(User $user)
    {
        //
    }

    public function edit(User $user)
    {
        //
    }

    public function update(Request $request, User $user)
    {
        //
    }

    public function destroy(User $user)
    {
        //
    }
}

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="d-flex justify-content-end mb-3">
        <a href="{{ route('register') }}" class="btn btn-primary">Add User</a>
    </div>

    <div class="card">

        <div class="card-header">Users</div>

        <div class="card-body">

            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Percentage</th>
                        <th>Type</th>
                        <th>Team</th>
                        <th>Actions</th>
                    </thead>
                    <tbody>
                        {{-- {{ dd($users) }} --}}
                        @foreach ($users as $user)
                            <tr>
                                <td>
                                    <img src="{{ $user->avatar }}" alt="">
                                </td>
                                <td>
                                    {{ $user->name }}
                                </td>
                                <td>
                                    {{ $user->email }}
                                </td>
                                <td>
                                    {{ $user->status }}
                                </td>
                                <td>{{ $user->percentage }}</td>
                                <td>
                                    {{ $user->role }}
                                </td>
                                <td>
                                    @if ($user->team_id)
                                        {{ $user->team->name }}
                                    @endif
                                </td>
                                <td>
                                    {{-- @if (!$user->isAdmin()) --}}
                                    <a href=""
                                    class="btn btn-outline-danger btn-sm"
                                    onclick="displayModalForm({{ $user }})"
                                    data-toggle="modal"
                                    data-target="#makeAdminModal">Make Admin</a>
                                    {{-- @endif --}}
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card-footer">
            {{ $users->links() }}
        </div>
    </div>

    <!-- MAKEADMIN Modal -->
    <div class="modal fade" id="makeAdminModal" tabindex="-1" role="dialog" aria-labelledby="makeAdminModal" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="makeAdminModal">MakeAdmin User</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <form action="" method="POST" id="makeAdminForm">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    Are your sure you want to Make Admin
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">MakeAdmin User</button>
                </div>
            </form>
        </div>
        </div>
    </div>
    <!-- END MakeAdmin Modal-->

@endsection

@section('page-level-scripts')
    <script type="text/javascript">
        function displayModalForm($user)
        {
            var url = '/users/' + $user.id + '/make-admin';
            $('#makeAdminForm').attr('action', url);
        }
    </script>
@endsection