routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes();

Route::get('/', function () { return view('home'); })->name('home');
Route::get('/login', function(){ return view('authentication/login'); })->name('login');
Route::get('/register', function(){ return view('authentication/register'); })->name('register');

Route::middleware(['auth'])->group(function () {
    Route::resource('users', 'UsersController');
    Route::resource('teams', 'TeamsController');
    Route::resource('tasks', 'TasksController');
    //checkTaskDeadline middleware is applied inside the TasksController

    Route::get('tasks/{task}/approve', 'TasksController@approve')->name('task.approve');
    Route::get('tasks/{task}/reassign', 'TasksController@reassign')->name('task.reassign');
    Route::get('tasks/{task}/resolve', 'TasksController@resolve')->name('task.resolve');
    Route::get('tasks/{task}/giveup', 'TasksController@giveup')->name('task.giveup');
    Route::get('tasks/{task}/assign', 'TasksController@assign')->name('task.assign');
});




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['name', 'team_id', 'deadline', 'status', 'completed_at'];

    /**
     * MUTATORTS
     */
    public function setTaskPivotStatusAttribute($status)
    {
        $this->record()->latest()->get()[0]->pivot->update(['status'=>$status]);
    }

    /**
     * ACCESSORS
     */
    public function getTaskPivotStatusAttribute()
    {
        return $this->record()->latest()->get()[0]->pivot->status;

    }
    public function getTaskPivotAttribute()
    {
        return $this->record[0]->pivot;
    }

    /**
     * HELPER METHODS
     */
    public function deadlineUpdate(){
        /**
         * This function will only call when the task's deadline is over
         * this function will set the status of both the tables i.e 'tasks' as well as pivot table i.e 'member_task' to 'UNRESOLVED'
         * Also if the member of the task has no more assigned tasks then the status will we set to VACANT.
         */
        $this->task_pivot->update(['status'=>'UNRESOLVED']);
        $this->update(['status'=> 'UNRESOLVED']);
        if($this->member[0]->tasks->where('status','ASSIGNED')->count() == 0)
        {
            $this->member[0]->update(['status'=> 'VACANT']);
        }
    }

    /**
     * RELATION SHIP METHODS
     */
    public function team(){
        return $this->belongsTo(Team::class, 'team_id', 'id');
    }
    public function member(){
        /**
         * Note to access the this member u have to use
         *      '$task->member[0]->name'
         *          instead of
         *      '$task->member->name'
         *  bcoz as we have used belongsToMany it is giving the collection, but inside that collection there is only one member
         *
         * NOTE: If one task has been assigned to many members, so $task->member[0] will give the latest member or the member to which thi task was assigned last
         *      I have used this 'member[0]' at mnay places, meaning that the current member of the task is member[0].
         *      thats why i have used the orderby in the member relation
         */
        return $this->belongsToMany(User::class,'member_task', 'task_id', 'member_id')->withPivot('member_id', 'status')->withTimestamps()->orderBy('pivot_created_at', 'DESC');
    }
    public function record(){
        return $this->belongsToMany(Task::class,'member_task','task_id')->withPivot('member_id', 'status', 'completed_at', 'reassign_count', 'is_giveup')->withTimestamps()->orderBy('pivot_created_at', 'DESC');
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\tasks\CreateTaskRequest;
use App\Http\Requests\UpdateTaskRequest;
use App\Task;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

class TasksController extends Controller
{
    public function __construct()
    {
        $this->middleware('checkAndUpdateTasksDeadline')->only('index');
        $this->middleware('checkTaskDeadline')->only('edit', 'resolve', 'giveup', 'reassign');
    }

    public function index()
    {
        // User::where('role', '!=', 'admin')->where('team_id', '!=', null)->get()->each(function($user){
        //     $user->calculatePercentage();
        // });
        if(auth()->user()->role == 'admin')
        {
            $tasks = Task::paginate(10);
        }
        elseif(auth()->user()->role == 'leader')
        {
            $tasks = auth()->user()->team->tasks()->paginate(10);
        }
        elseif(auth()->user()->role == 'member')
        {
            $tasks = auth()->user()->tasks()->paginate(10);
        }
        return view('tasks.index', compact(
            'tasks'
        ));
    }

    public function create()
    {
        return view('tasks.create');
    }

    public function store(CreateTaskRequest $request)
    {
        $member = null;
        if($request->member)
        {
            $member = $request->member;
        }
        else
        {
            $member = auth()->user()->team->members()->pluck('id')->random();
        }
        $task = Task::create([
            'name' => $request->name,
            'team_id' => auth()->user()->team->id,
            'status' => 'ASSIGNED',
            'deadline' => $request->deadline
        ]);

        $task->record()->attach($member, ['status' => 'ASSIGNED', 'member_id' => $member]);

        //Session storage
        session()->flash('success', 'Task Created Successfully');

        //redirect
        return redirect(route('tasks.index'));

    }

    public function show(Task $task)
    {
        //
    }

    public function edit(Task $task)
    {
        $members = auth()->user()->team->members;
        $action = 'edit';
        return view('tasks.edit', compact(
            'task',
            'action',
            'members'
        ));
    }

    public function update(UpdateTaskRequest $request, Task $task)
    {
        if(isset($request->name) != null)
        {
            //If we came inside this . its meanss that this action is edit
            $task->update(['name' => $request->name, 'deadline' => $request->deadline]);

            //Session storage
            session()->flash('success', 'Task Updated Successfully');
        }
        else
        {
            //If we came inside this . its meanss that this action is 'assign'
            $member = User::find($request->member);
            $task->update(['deadline' => $request->deadline]);
            $task->record()->attach($member->id, ['status' => 'ASSIGNED', 'member_id' => $member->id]);
            $member->updateUserStatus();

            //Session storage
            session()->flash('success', 'Task Assigned Successfully');
        }

        //redirect
        return redirect(route('tasks.index'));
    }

    public function destroy(Task $task)
    {
        //
    }

    public function approve(Task $task)
    {
        $completedDate = Carbon::createFromFormat('Y-m-d H:i:s', $task->task_pivot->completed_at );
        $task->task_pivot->update(['status' => 'RESOLVED']);
        $task->update(['status'=>'RESOLVED', 'completed_at'=>$completedDate]);
        $task->member[0]->calculatePercentage();
        $task->member[0]->updateUserStatus();
        return redirect()->back();
    }
    public function reassign(Task $task)
    {
        $task->task_pivot->update(['status' => 'ASSIGNED', 'completed_at' => null, 'reassign_count' => $task->task_pivot->reassign_count + 1]);
        return redirect()->back();
    }
    public function resolve(Task $task)
    {
        $task->task_pivot->update(['status' => 'REQUEST_RESOLVE', 'completed_at' => Carbon::now()]);
        return redirect()->back();
    }
    public function giveup(Task $task)
    {
        $task->task_pivot->update(['status' => 'UNRESOLVED', 'is_giveup' => 1]);
        if($task->member->count() == $task->team->members->count())
        {
            $task->update(['status' => 'UNRESOLVED']);
        }
        $task->member[0]->calculatePercentage();
        $task->member[0]->updateUserStatus();
        return redirect()->back();
    }
    public function assign(Task $task)
    {
        if($this->authorize('assign', $task))
        {
            $members = auth()->user()->team->members;
            $action = 'assign';
            return view('tasks.edit', compact(
                'task',
                'action',
                'members'
            ));
        }
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="card ">
        <div class="card-header">Add Task</div>
        <div class="card-body">
            <form action="{{ route('tasks.store') }}" method="POST">
                @csrf
                <div class="row">
                    <div class="form-group col-md-5">
                        <label for="name">Name</label>
                        <input type="text"
                                value="{{ old('name') }}"
                                class="form-control"
                                name="name" id="name">
                        @error('name')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="col-md-1"></div> {{-- Extra div here --}}

                    <div class="form-group col-md-4">
                        <label for="deadline">Deadline</label>
                        <input type="date"
                                value="{{ old('deadline') }}"
                                class="form-control"
                                name="deadline" id="deadline">
                        @error('deadline')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="form-group col-md-5">
                        <label for="member">Member</label>
                        <select name="member" id="member" class="form-control select2" >
                                <option value="" disabled selected>Select ..</option>
                            @foreach (auth()->user()->team->members()->where('role', '!=', 'leader')->get() as $member)
                                <option value="{{ $member->id }}">{{ $member->name }}</option>
                            @endforeach
                        </select>
                        @error('member')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="col-md-1"></div> {{-- Extra div here --}}

                    <div class="form-group pl-4 pt-4 col-md-4">
                        <div class="form-check">
                            <label class="form-check-label">
                            <input type="checkbox" class="form-check-input"
                                    name="randomTaskAssignToMemberCheckbox" id="randomTaskAssignToMemberCheckbox"
                                    value="randomTaskAssignToMemberCheckboxSelected"
                                    {{-- checked --}}
                                    onchange="checkboxChange()">
                            Select for randomly task assign.
                            </label>
                        </div>
                        @error('randomTaskAssignToMemberCheckbox')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Add Task</button>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

    <script>
        flatpickr("#deadline", {
            enableTime: true
        });
        $('.select2').select2({
            placeholder : 'Select..'
        });

        function checkboxChange(){
            var checkBox = document.getElementById('randomTaskAssignToMemberCheckbox');
            var selectElement = document.getElementById('member');

            if(checkBox.checked){
                selectElement.disabled = true;
            }
            else{
                selectElement.disabled = false;
            }
        }
    </script>
@endsection

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card ">
        <div class="card-header">{{ $action }} Task</div>
        <div class="card-body">
            <form action="{{ route('tasks.update', $task) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="form-group col-md-5">
                        <label for="name">Name</label>
                        <input type="text"
                                value="{{ old('name', $task->name) }}"
                                class="form-control"
                                name="name" id="name"
                                @if ($action == 'assign')
                                    disabled
                                @endif
                                >
                        @error('name')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>

                    <div class="col-md-1"></div> {{-- Extra div here --}}

                    <div class="form-group col-md-4">
                        <label for="deadline">Deadline</label>
                        <input type="text"
                                value="{{ $task->deadline }}"
                                class="form-control"
                                name="deadline" id="deadline">
                        @error('deadline')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                    <div class="form-group col-md-5">
                        <label for="member">Member</label>
                        <select name="member" id="member" class="form-control select2"
                            @if ($action == 'edit')
                                disabled
                        >
                            <option value="{{ $task->member[0]->id }}" disabled selected>{{ $task->member[0]->name }}</option>
                            @else
                        >
                                <option value="" disabled selected>Select ..</option>
                                @foreach ($members as $member)
                                    <option value="{{ $member->id }}"
                                        @foreach ($task->member as $task_member)
                                            @if ($member->name == $task_member->name)
                                                disabled
                                            @endif
                                        @endforeach
                                        >
                                        {{ $member->name }}
                                    </option>
                                @endforeach
                            @endif

                        </select>
                        @error('member')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">{{ $action }} Task</button>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('page-level-scripts')
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

    <script>
        flatpickr("#deadline", {
            enableTime: true
        });
        $('.select2').select2({
            placeholder : 'Select..'
        });

        function checkboxChange(){
            var checkBox = document.getElementById('randomTaskAssignToMemberCheckbox');
            var selectElement = document.getElementById('member');

            if(checkBox.checked){
                selectElement.disabled = true;
            }
            else{
                selectElement.disabled = false;
            }
        }
    </script>
@endsection

@section('page-level-styles')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')

    @can('create', App\Task::class)
        <div class="d-flex justify-content-end mb-3">
            <a href="{{ route('tasks.create') }}" class="btn btn-primary">Add Task</a>
        </div>
    @endcan

    <div class="card">

        <div class="card-header">Tasks</div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <th>Name</th>
                        <th>Team</th>
                        @if (auth()->user()->role != 'member')
                            <th>Assigned To </th>
                        @endif
                        <th>reassign_count</th>
                        <th>is_giveup</th>
                        <th>Status</th>
                        <th>Deadline</th>
                        <th>Actions</th>
                    </thead>
                    <tbody>
                        {{-- {{ dd($tasks) }} --}}
                        @foreach ($tasks as $task)
                            <tr>
                                <td>
                                    {{ $task->name }}
                                </td>
                                <td>
                                    {{ $task->team->name }}
                                </td>
                                @if (auth()->user()->role != 'member')
                                    <td>
                                        {{ $task->member[0]->name }}
                                    </td>
                                @endif
                                <td>
                                    {{ $task->task_pivot->reassign_count }}
                                </td>
                                <td>
                                    {{ $task->task_pivot->is_giveup }}
                                </td>
                                <td>
                                    @if (auth()->user()->role == 'member')
                                        {{ $task->task_pivot_status }}
                                    @else
                                        {{ $task->status }}
                                    @endif
                                </td>
                                <td>
                                    {{ $task->deadline }}
                                </td>
                                {{-- actions:START --}}
                                <td>
                                    @can('update', $task)
                                        <a href="{{ route('tasks.edit', $task->id) }}" class="btn btn-outline-primary btn-sm">Edit</a>
                                    @elsecan('approveOrReassign', $task)
                                        <a href="{{ route('task.approve', $task->id) }}" class="btn btn-outline-success btn-sm">Approve</a>
                                        <a href="{{ route('task.reassign', $task->id) }}" class="btn btn-outline-primary btn-sm">Reassign</a>
                                    @elsecan('resolveOrGiveup', $task)
                                        <a href="{{ route('task.resolve', $task->id) }}" class="btn btn-outline-primary btn-sm">Resolve</a>
                                        <a href="{{ route('task.giveup', $task->id) }}" class="btn btn-outline-danger btn-sm">Give up</a>
                                    @elsecan('assign', $task)
                                        <a href="{{ route('task.assign', $task->id) }}" class="btn btn-outline-danger btn-sm">Assign</a>
                                    @else
                                        {{-- {{ date("Y-m-d / h:i:sa", strtotime($task->deadline))  }} --}}
                                        {{ 'No Actions' }}
                                        {{-- @if (\Carbon\Carbon::now() > $task->deadline)
                                        @endif --}}
                                    @endcan
                                </td>
                                {{-- actions:END --}}
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card-footer">
            {{ $tasks->links() }}
        </div>
    </div>

@endsection